config/routes.rb
Rails.application.routes.draw do

    resources :users do 
    	get :following, :followers
    end
    resources :posts do 
      resources :comments
    end
    # resources :relationships, only: [:create, :destroy]

    get '/follow/:id', to: 'relationships#create', as: 'follow'
    get '/unfollow/:id', to: 'relationships#destroy', as: 'unfollow'

     get '/signin', to: 'sessions#new'
     post '/signin', to: 'sessions#create'
     get '/logout', to: 'sessions#destroy'


  # You can have the root of your site routed with "root"
  root 'users#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	scope :created_before, ->(time) { where("created_at < ?", time) }
	validates :body, length: {in: 5..7000}

	def display_status
		if self.status == 0
			"closed"
		elsif self.status == 1
			"open"
		elsif self.status == 2
			"pending"
		else
			"not set"
		end
	end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_many :active_relationships, class_name: "Relationship",
									foreign_key: "follower_id",
									dependent:  :destroy
	has_many :passive_relationships, class_name: "Relationship",
									 foreign_key: "followed_id",
									 dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

	has_attached_file :image, styles: {small:"64x64>", med: "100x100",large: "200x200>", icon: "32x32>"}
					  # :url  => "/assets/user/:id/:style/:basename.:extension",
       #                :path => ":rails_root/public/user/images/:id/:style/:basename.:extension"


validates_attachment_presence :image, on: :update
validates_attachment_size :image, :less_than => 5.megabytes, on: :update
validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png'], on: :update

validates_presence_of :email, :password, :name




end
	
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_user
  	session[:user_id] ? User.find(session[:user_id]) : nil
  	end

  	def current_post
  	 	params[:post_id] ? Post.find(params[:post_id]) :nil
  	end

  	
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_comment, only: [:new, :edit, :show, :destroy]

  def index
  	@comments = Comment.all 
  end

  def new
  	if current_user
     @comment = Comment.new
     @post = Post.find(params[:post_id])
    else
      flash[:notice] = "Please sign in first."
      redirect_to signin_path
    end

  end

  def show
  end

  def edit
  end

  def create
  	@comment = Comment.create(comment_params)
    @comment.user = current_user
    @comment.post = current_post
    redirect_to :back , notice: "Your comment has been posted."
  end

  def destroy
  	@comment.destroy
    redirect_to post_path(params[:post_id]), notice: "Comment deleted."
  end

  private 

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title, :body).merge(user_id: current_user.id, post_id: current_post.id)
  end










end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all
  end

  def new
    if current_user
     @post = Post.new

    else
      flash[:notice] = "Please sign in first."
      redirect_to signin_path
    end
  end

  def edit
    

  end

  def show
    @comment = Comment.new
    
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "New post created."
    else 
      render :new
    end
    
    
  end

  def update
    @post.update(post_params)
    redirect_to @post, notice: "Post succesfully updated."
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post deleted."
  end

  private



  def set_post
    @post = Post.find(params[:id])
  end  

  def post_params
    params.require(:post).permit(:title, :body).merge(user_id: current_user.id)
  end

 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	

  def create
  	 @relationship = Relationship.create(follower_id: current_user.id, followed_id: params[:id])
  	 @user = User.find(params[:id])
  	 redirect_to users_path, notice: 'User followed'
  end

  def destroy
  	@relationship = Relationship.find_by(follower_id: current_user.id, followed_id: params[:id])
    @relationship.destroy
    redirect_to users_path, notice: 'User Unfollowed'
  end

  
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.find_by(email: params[:email])
		if @user and @user.password == params[:password]
			flash[:notice] = "Successfully signed in!"
			session[:user_id] = @user.id
		else
			flash[:alert] = "Something went wrong."
		end
			redirect_to root_path
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged out."
		redirect_to root_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show, :destroy, :following, :followers]
	
  def index
  	@users = User.all
    if current_user 
      redirect_to posts_path
    else
      
    end

  end

  def new
  	@user = User.new
  end

  def edit
    @user = current_user
  end

  def show
  end

  def create
  	@user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
  	   redirect_to @user, notice: "New user created."
    else 
      render :new
    end

  end

  def update
  	
  	
     if @user.update(user_params)
      redirect_to @user, notice: "User successfully updated."
    else 
      render :edit
    end
  end

  def destroy
  	@user.destroy
  	redirect_to users_path, notice: "User was deleted."
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def set_user
  	@user = User.find(params[:id])
  end

def user_params
    params.require(:user).permit(:name, :bio, :email, :password, :image)
  end

    def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
  		session[:user_id] ? User.find(session[:user_id]) : nil
  	end

  	def current_post
  	 params[:id] ? Post.find(params[:id]) : nil
  	end

  

  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def set_comment
    @comment = Comment.find(params[:id])
  	end

	def timestamp
		time_ago_in_words(set_comment.created_at) 
	end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_commentform.html.erb
<%= form_for [@post, @comment] do |s| %>

	<%= s.text_area :body, placeholder: "Comment here bruh..." %><br />

	<%= s.submit %>

<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render 'commentform' %>
<br />
<%= link_to 'cancel', posts_path %>

app/views/comments/index.html.erb
<h1>Listing all comments</h1>

<% if current_user %>
	<p><%= link_to 'new comment', new_post_comment_path %></p>
<% end %>

<ul>
	<% @comments.each do |comment| %>
		<li>
			<%= link_to comment.title, post_comments_path(comment) %>
			<!-- test -->
			<% if current_user == current_post %>
			 | 
			<%= link_to 'edit', edit_post_comment_path(comment) %> |
			<%= link_to 'delete', post_comments_path(comment), method: :delete, data: {confirm: "Really delete this comment?"} %>
			<% end %>
			
		</li>
	<% end %>
</ul>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'commentform' %>
<br />
<%= link_to 'cancel', comments_path %>

app/views/comments/show.html.erb
<h1><%= @comment.title %></h1>
<p><%= @comment.body %></p>

<%= link_to 'new comment', new_comment_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mumblr</title>
 <link href='http://fonts.googleapis.com/css?family=Days+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
	<% if current_user != nil %>
	<a class="usernavpic"><%= image_tag current_user.image.url(:small)%> </a> <h3 class="usernavname">Welcome <%=current_user.name%>! </h3>
	<h1 class="mumblrlogo"><%= "Mumblr." %></h1>
	<%else%>
		<h1 class="mumblrlogo2"><%= "Mumblr." %></h1>
	<%end%>
		<!-- <h1 class="mumblrlogo">Mumblr.</h1> -->
	
		<!-- <p><%= link_to 'New here? Sign Up!', new_user_path %></p> -->
		

		<!-- <%= render 'shared/login' %> -->
	</header>

	
		<div class="signoutlink">
			<br>

			<a class="notice"><%= flash[:notice] if flash[:notice] %></a>
				<a class="alert"><%= flash[:alert] if flash[:alert] %></a>
				<br>

		</div>
	

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li> <%= message %></li>
		<% end %>
	</ul>
	
<%end%>


<%= form_for @post do |f| %>

	<%= f.text_field :title, placeholder: "Enter Title Here..." %><br />
	
	<%= f.text_area :body, placeholder: "Enter Body Here..." %><br />
	<a><button type="button" class="formbuttons"><%= link_to 'Cancel', posts_path %></button></a>
	<%= f.submit :class => "formbuttons"%>


<% end %>

app/views/posts/edit.html.erb
<div class="posttopmargin">
<br>
<div class="newpostbody">
	<div class="editpostcontent">
		<h1>Edit Post</h1>
		<%= render 'form' %>
		<br />
	</div>	
</div>


<div class="rightnav">
	<div>
		<ul>
			<li id = "returnhome"><a><%= link_to 'Home', posts_path %></a></li>
			<li id = "newpost"><a><%= link_to 'New Post', new_post_path %></a></li>
			<li id = "viewprofile"><a><%= link_to 'View Profile', user_path(current_user)%></a></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><a><%= link_to 'Account Settings', edit_user_path(current_user) %></a></li>
			<li id = "signout"><a><%= link_to 'sign out', logout_path, method: :delete %></li>


		</ul>

	</div>
	
</div>

app/views/posts/index.html.erb
<div class="posttopmargin">
<br>
<!-- <div class="welcome">
	<h1>Welcome <%= current_user.name %>!</h1>

</div> -->



<div class="postsbody">

	<h1>Lastest Posts!</h1>
	
		
			<% @posts.reverse.each do |post| %>
			<ul>
			<div class="usericon">	<%= image_tag post.user.image.url(:small) %></div>
					<li class="poststyling">
						
						
						<div class="posttitle">
							
						<%= link_to post.title, post_path(post) %> 
					
						<span id ="timecreated">Posted by: <%= post.user.name %> on <%= post.created_at.strftime("%b. %d %Y") %> </span>

						</div>
						<br>
						<div class="postbodystyling">
						<%= post.body[0...1000] %> ...
						</div>
						
					
						<div id="spaceme"></div>
						<p class="readmore"><%= link_to "Read More...", post_path(post) %></p>
					</li>
						</ul>
				<% end %>

	
				

				</div>






<div class="rightnav">
	<div class="navbartext">
		<ul id=""cl-effect-1"">
			<li id = "returnhome"><div class="buttonboxhome"><a><%= link_to 'Home', posts_path %></a></div></li>
			<li id = "newpost"><div class="buttonboxnew"><a><%= link_to 'New Post', new_post_path %></a></div></li>
			<li id = "viewprofile"><div class="buttonboxview"><a><%= link_to 'View Profile', user_path(current_user)%></a></div></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><div class="buttonboxsettings"><a><%= link_to 'Account Settings', edit_user_path(current_user) %></a></div></li>
			<li id = "signout"><div class="buttonboxsignout"><a><%= link_to 'sign out', logout_path, method: :delete %></a></div></li>


		</ul>

	</div>
	
</div>


</div>

app/views/posts/new.html.erb
<div class="posttopmargin">
<br>
	<div class="newpostbody">
		<div class="newpostcontent">
			
			<h1 class = "newposthead">New Post</h1>
			<%= render 'form' %>
			<br />
			
		</div>
	</div>




<div class="rightnav">
	<div>
		<ul>
			<li id = "returnhome"><a><%= link_to 'Home', posts_path %></a></li>
			<li id = "newpost"><a><%= link_to 'New Post', new_post_path %></a></li>
			<li id = "viewprofile"><a><%= link_to 'View Profile', user_path(current_user)%></a></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><a><%= link_to 'Account Settings', edit_user_path(current_user) %></a></li>
			<li id = "signout"><a><%= link_to 'sign out', logout_path, method: :delete %></li>


		</ul>

	</div>
	
</div>





</div>

app/views/posts/show.html.erb
<div class="posttopmargin">
<br>

<div class="showpostbody">
	<h1><%= @post.title %></h1>
	<p id="postbodyformat"><%= @post.body %></p>
	 
	 <% if current_user == current_post.user %>
				<%= link_to 'edit', edit_post_path %> |
				<%= link_to 'delete', post_path, method: :delete, data: {confirm: "Really delete this post?"} %>
	<% end %> 

<div class="commentbox">
	<h3>Comment </h3>
	<%= render 'comments/commentform' %>
	<br>
</div>
	<h3>Post Comments</h3>
	<% current_post.comments.last(10).reverse.each do |c| %>
	<div class="commentborders">
		<span><%= c.body %></span>
		<p> Posted by: <%= c.user.name %></p>
		<p><%= c.created_at.strftime("%b. %d %Y") %></p>
		<% if current_user == set_comment.user%>
				<%= link_to 'edit', edit_post_path %> |
				<%= link_to 'delete', post_comment_path(current_post, c), method: :delete, data: {confirm: "Really delete this comment?"} %>
	<% end %> 
	</div>
	<% end %>
</div>
<div class="rightnav">
	<div>
		<ul>
			<li id = "returnhome"><a><%= link_to 'Home', posts_path %></a></li>
			<li id = "newpost"><a><%= link_to 'New Post', new_post_path %></a></li>
			<li id = "viewprofile"><a><%= link_to 'View Profile', user_path(current_user)%></a></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><a><%= link_to 'Account Settings', edit_user_path(current_user) %></a></li>
			<li id = "signout"><a><%= link_to 'sign out', logout_path, method: :delete %></li>



		</ul>

	</div>
	
</div>



</div>

app/views/shared/_login.html.erb
<% if current_user %>
	<p>Hello <%= current_user.name %> | 
		<%= link_to 'sign out', logout_path, method: :delete %>
			| 
		<%= link_to 'new post', new_post_path %>
	</p>
<% else %>
	<%= form_tag(signin_path, method: :post) do %>
		<%= label_tag %>
		<%= email_field_tag :email, nil, placeholder: 'Email' %>
		<br>
		<%= label_tag %>
		<%= password_field_tag :password, nil, placeholder: 'Password' %>
		<br>
		<a><button type="button" class="formbuttons"><%= link_to "Sign up", new_user_path %></button></a>
		<%= submit_tag "login", :class=> "formbuttons" %>

		
	<% end %>
<% end %>

app/views/users/_editform.html.erb
<% if @user.errors.any? %>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
			
			 <li><%= message %></li>

		<% end %>
	</ul>

<% end %>

<%= form_for @user, :html => {:multipart => true} do |f| %>
	
	<%= f.text_field :name, placeholder: "Name" %><br />
	
	
	<%= f.email_field :email, placeholder: "Email"  %><br />
	
	
	<%= f.text_area :bio, placeholder: "Bio"  %><br />
	
	
	<%= f.password_field :password, placeholder: "Password", value: current_user.password %><br />
	<p>Upload A Profile Pic!</p>
	<%= f.file_field :image %> <br>

	
	<%= f.submit :class => 'formbuttons'%>
<% end %>

app/views/users/_followform.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
			
			 <li><%= message %></li>

		<% end %>
	</ul>

<% end %>

<%= form_for @user do |f| %>
	
	<%= f.text_field :name, placeholder: "Name" %><br />
	
	
	<%= f.email_field :email, placeholder: "Email"  %><br />
	
	
	<%= f.text_area :bio, placeholder: "Bio"  %><br />
	
	
	<%= f.password_field :password, placeholder: "Password"%><br />

	<%= f.submit :class => 'formbuttons'%>
<% end %>

app/views/users/edit.html.erb
<div class="posttopmargin">
<br>
	<div class="edituserbody">
		<div class="editusercontent">
			<h1>Edit User</h1>
			<%= render 'editform' %>
		</div>
	</div>

	<div class="rightnav">
	<div>
		<ul>
			<li id = "returnhome"><p><%= link_to 'Post', posts_path %></p></li>
			<li id = "newpost"><p><%= link_to 'New Post', new_post_path %></p></li>
			<li id = "viewprofile"><p><%= link_to 'View Profile', user_path(current_user)%></p></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><p><%= link_to 'Account Settings', edit_user_path(current_user) %></p></li>
			<li id = "signout"><p><%= link_to 'sign out', logout_path, method: :delete %></p></li>


		</ul>

	</div>
	
</div>
</div>

app/views/users/index.html.erb
<!-- <h1>Recent Users</h1>



<ul>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user_path(user) %> | 
			<%= link_to 'edit', edit_user_path(user) %> |
			<%= link_to 'delete', user_path(user), method: :delete, data: {confirm: "Really delete this user?"} %>
		</li>
	<% end %>
</ul> -->

	<div class="loginbody">

		<div class="loginbox"> 
			<h1>Log In</h1>
	
				
			<%= render 'shared/login' %>
			</div>

	</div>	

app/views/users/new.html.erb
<div class="signinbody">

	<div class="newuserbox">
		<h1>Sign Up!</h1>
		<%= render 'form' %>
		<br />
		<a><button type="button" class="formbuttons"><%= link_to 'cancel', users_path %></button></a>
	</div>
</div>	

app/views/users/show.html.erb
<div class="posttopmargin">
<br>
	<div class ="userprofilebody">
		<div class="userprofilecontent">

			

			
		<div class="userimageleft">
			<h1><%= @user.name %></h1>
			<%= image_tag @user.image.url(:small) %>

			<p>(<%= @user.email %>) <%= @user.bio %></p>
		</div>


		<div class="userbioposts">
			<h3><%= @user.name %>'s Posts</h3>

			<ul>
				<% @user.posts.each do |post| %>
				<li>
				<div class="userposttitle">
							
					<%= link_to post.title, post %> 
					
					<span id ="timecreated">Posted by: <%= post.user.name %> on <%= post.created_at.strftime("%b. %d %Y") %> </span>

				</div>

				<div class="userpostbody">
						<%= post.body[0...1000] %> ...
				</div>	

				<p class="readmore"><%= link_to "Read More...", post_path(post) %></p>

				</li>
				<% end %>
			</ul>
		</div>
<br>
<% if @user.id == current_user.id %>
<%= link_to 'edit', edit_user_path(@user) %>
<%= link_to 'back', users_path %> | 
<% else %>
<%= link_to 'back', users_path %>
<%end%>
<ul>



<%@relationship = Relationship.find_by(follower_id: current_user.id, followed_id: params[:id])%>


<% if @user.id == current_user.id %>
						This is You!
						<%elsif @relationship != nil%>
						<%= link_to 'Unfollow', unfollow_path(@user)%>
						<%else%>
						<%= link_to 'Follow', follow_path(@user)%>
						<%end%>







<%if @user.followers.count >= 2 || @user.followers.count == 0%>
<h4><%= @user.name%> Has <%= @user.followers.count%> Followers</h4>
<%else%>
<h4><%= @user.name%> Has <%= @user.followers.count%> Follower</h4>
<%end%>





<% @user.followers.each do |user| %>
	<li><%= user.name %></li>
<% end %>
</ul>

			
		</div>
	</div>

	<div class="rightnav">
	<div>
		<ul>
			<li id = "returnhome"><p><%= link_to 'Home', posts_path %></p></li>
			<li id = "newpost"><p><%= link_to 'New Post', new_post_path %></p></li>
			<li id = "viewprofile"><p><%= link_to 'View Profile', user_path(current_user)%></p></li>
			<li id = "followusers"></li>
			<li id = "accountsettings"><p><%= link_to 'Account Settings', edit_user_path(current_user) %></p></li>
			<li id = "signout"><p><%= link_to 'sign out', logout_path, method: :delete %></p></li>


		</ul>

	</div>
	
</div>



</div>